apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kagent-system/namespace.yaml  # Ensure namespace exists first
  - kagent-helm-repo.yaml
  - kagent-crds-release.yaml
  - kagent-release.yaml