apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: perf-lab
  namespace: flux-system
spec:
  image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/perf-lab/perf-lab
  provider: gcp
  interval: 1m
