apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      version: '2.8.2'
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      interval: 1m
  values:
    controllermanager:
      controller: 
        replicaCount: 2
