apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-gcp
  namespace: crossplane-system
  annotations:
    iam.gke.io/gcp-service-account: crossplane-gke-sa@${PROJECT_ID}.iam.gserviceaccount.com
