apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-wi
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-provider-gcp
      annotations:
        iam.gke.io/gcp-service-account: crossplane-gke-sa@${PROJECT_ID}.iam.gserviceaccount.com
