apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-wi
spec:
  deploymentTemplate:
    spec:
      template:
        spec:
          serviceAccountName: crossplane-provider-gcp
