version: "3"

includes:
  setup:
    taskfile: ./tasks/setup.yaml
    dir: .
  debug:
    taskfile: ./tasks/test-and-debug.yaml
    dir: .
  mcp:
    taskfile: ./tasks/mcp.yaml
    dir: .
  port-forward:
    taskfile: ./tasks/port-forward.yaml
    dir: .
