# https://github.com/christian-posta/scripted-solo-demos/blob/master/agentgateway/kubernetes/gateway.yaml
# with some changes
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: agentgateway
spec:
  controllerName: kgateway.dev/kgateway
  parametersRef:
    group: gateway.kgateway.dev
    kind: GatewayParameters
    name: kgateway
    namespace: mcp
