---
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: mcp-listener-set
  namespace: mcp
spec:
  parentRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: agent-gateway
    namespace: mcp
  listeners:
  - name: mcp
    protocol: kgateway.dev/mcp  # Use the custom MCP protocol
    port: 3000
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-route
  namespace: mcp
spec:
  parentRefs:
  - kind: XListenerSet
    group: gateway.networking.x-k8s.io
    name: mcp-listener-set
    namespace: mcp
    sectionName: mcp
  rules:
  - backendRefs:
    - name: mcp-everything-service
      port: 3000

