---
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: mcp-website-fetcher
  namespace: kagent
spec:
  parentRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: shared-mcp-kgateway
    namespace: kgateway-system
  listeners:
  - name: mcp
    protocol: kgateway.dev/mcp
    port: 3000
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-website-fetcher
  namespace: kagent
spec:
  parentRefs:
  - kind: XListenerSet
    group: gateway.networking.x-k8s.io
    name: mcp-website-fetcher
    namespace: kagent
    sectionName: mcp
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: mcp-website-fetcher
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: "/"
