# step 4 - https://kgateway.dev/docs/mcp/
# above doc is not up to date, at this moment
# use https://agentgateway.dev/docs/targets/mcp/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
  namespace: mcp
spec:
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: mcp-gateway
        image: ghcr.io/agentgateway/agentgateway:latest-ext
        args:
          - --file=/config/config.json
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            memory: 800Mi
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: mcp-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: mcp
spec:
  selector:
    app: mcp-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      appProtocol: kgateway.dev/mcp
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-gateway-config
  namespace: mcp
data:
  config.json: |
    {
      "type": "static",
      "listeners": [
        {
          "name": "sse",
          "protocol": "MCP",
          "sse": {
            "address": "[::]",
            "port": 3000
          }
        }
      ],
      "targets": {
        "mcp": [
          {
            "name": "everything",
            "stdio": {
              "cmd": "npx",
              "args": [
                "@modelcontextprotocol/server-everything"
              ]
            }
          }
        ]
      }
    }
