# step 4 - https://kgateway.dev/docs/mcp/
# above doc is not up to date, at this moment
# use https://agentgateway.dev/docs/targets/mcp/
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: mcp
spec:
  selector:
    app: mcp-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      appProtocol: kgateway.dev/mcp
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-gateway-config
  namespace: mcp
data:
  config.json: |
    {
      "type": "static",
      "listeners": [
        {
          "name": "sse",
          "protocol": "MCP",
          "sse": {
            "address": "[::]",
            "port": 3000
          }
        }
      ],
      "targets": {
        "mcp": [
          {
            "name": "everything",
            "stdio": {
              "cmd": "npx",
              "args": [
                "@modelcontextprotocol/server-everything"
              ]
            }
          }
        ]
      }
    }
