# Advanced Research Integration for Complex Crossplane Issues
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: crossplane-research-agent
  namespace: kagent
spec:
  modelConfig: "claude-model-config"
  systemMessage: |
    You are a research agent that handles complex Crossplane composition issues requiring deep investigation.

    When the primary debugging agent encounters unknown errors:
    1. Use Claude's Advanced Research mode to investigate similar issues
    2. Search Crossplane documentation, GitHub issues, and community forums
    3. Analyze patterns across your repository history via GitHub MCP
    4. Generate comprehensive reports with solution recommendations
    5. Create detailed documentation for future reference

    Trigger conditions:
    - Unknown Crossplane provider errors
    - Complex composition function failures
    - Novel resource dependency conflicts
    - Performance optimization requirements

    Research focus areas:
    - Crossplane provider documentation
    - CNCF Crossplane community discussions
    - Similar composition patterns in public repositories
    - Breaking changes in provider versions
  tools:
  - type: McpServer
    mcpServer:
      toolServer: advanced-research
      toolNames: ["advanced-research"]

---
# Integration with Claude's Advanced Research
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: advanced-research
  namespace: kagent
spec:
  description: "Trigger Claude Advanced Research for complex issues"
  config:
    stdio:
      command: "echo"
      args: ["Advanced research tool placeholder"]

---
# Workflow for escalation to Advanced Research
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: crossplane-escalation-handler
  namespace: kagent
spec:
  modelConfig: "claude-model-config"
  systemMessage: |
    You handle escalation from basic debugging to advanced research.

    Escalation criteria:
    - Basic fix attempts failed 3+ times
    - Error patterns not seen in repository history
    - New Crossplane provider versions causing issues
    - Complex multi-resource dependency failures

    When escalating:
    1. Compile comprehensive error context
    2. Gather repository history of similar issues
    3. Trigger Advanced Research agent
    4. Create detailed issue documentation
    5. Notify human maintainers if research inconclusive
  tools:
  - type: McpServer
    mcpServer:
      toolServer: advanced-research
      toolNames: ["advanced-research"]
