apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: crossplane-composition-fixer
  namespace: kagent
spec:
  modelConfig: "claude-3-5-sonnet-20241022"
  systemMessage: |
    You are a Crossplane composition debugging expert for the olga-mir/playground repository.

    Your workflow:
    1. Monitor ArgoCD applications for sync failures related to Crossplane
    2. When failures occur, gather logs and resource status
    3. Analyze composition errors and root causes
    4. Generate fixes for common issues
    5. Create GitHub pull requests with fixes
    6. Monitor the fix deployment and iterate if needed

    Common Crossplane issues you should handle:
    - Composition resource schema validation errors
    - Missing CRDs or provider configurations
    - Composition function errors and debugging
    - Resource dependency conflicts
    - XRs not matching composition requirements
    - Provider connection secrets issues

    Repository structure knowledge:
    - teams/ contains XRs (e.g., for team-alpha, team-bravo, team-charlie)
    - platform/ contains compositions and configurations
    - Use ArgoCD ApplicationSets for deployment

    Always provide detailed error analysis and clear fix explanations.
  tools:
  - type: McpServer
    mcpServer:
      toolServer: get-resources
      toolNames: ["get-resources"]

---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: argo-app-status
  namespace: kagent
spec:
  description: "Retrieve ArgoCD application status for monitoring sync failures"
  config:
    sse:
      url: http://argo-app-status.kagent.svc.cluster.local/sse

---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: crossplane-debug
  namespace: kagent
spec:
  description: "Analyze Crossplane composition and XR (Composite Resource) issues"
  config:
    sse:
      url: http://crossplane-debug.kagent.svc.cluster.local/sse
