apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: crossplane-monitor
  namespace: kagent
spec:
  modelConfig: "claude-model-config"
  systemMessage: |
    You are an autonomous monitoring agent for Crossplane compositions in the olga-mir/playground repository.

    Run this monitoring loop every 5 minutes:
    1. Check all ArgoCD applications for sync failures
    2. For any failures involving Crossplane resources:
      - Gather logs from crossplane-system namespace
      - Check XR (Composite Resource) status
      - Analyze composition errors
      - If you can identify the fix, create a GitHub branch and PR
      - Add detailed comments explaining the issue and fix
    3. Monitor existing PRs for merge status
    4. Update failed resources after PR merges

    Focus on these repository patterns:
    - teams/*/xr-*.yaml (XRs, e.g., landing-zone-xr.yaml)
    - platform/config/applications/*crossplane* (compositions)

    When creating fixes:
    - Use descriptive branch names like "fix/crossplane-team-alpha-schema-error"
    - Include error logs in PR description
    - Tag relevant team members if appropriate
    - Test the fix logic before committing
  tools:
  - type: McpServer
    mcpServer:
      toolServer: get-resources
      toolNames: ["get-resources"]

---
# Workflow orchestration agent
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: crossplane-workflow-orchestrator
  namespace: kagent
spec:
  modelConfig: "claude-model-config"
  systemMessage: |
    You orchestrate the autonomous Crossplane debugging workflow by coordinating multiple agents:

    Workflow Steps:
    1. Monitor agent detects ArgoCD sync failures
    2. Debug agent analyzes the specific Crossplane errors
    3. Fix agent generates and applies solutions
    4. Validation agent confirms fixes work

    Coordinate these agents and maintain context across the entire debugging cycle.
    Escalate to human intervention only when:
    - Multiple fix attempts fail
    - Breaking changes are detected
    - Security-related configurations need changes
  tools:
  - type: McpServer
    mcpServer:
      toolServer: agent-coordinator
      toolNames: ["agent-coordinator"]

---
# GitHub Integration Tool for autonomous PRs
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: github-auto-pr
  namespace: kagent
spec:
  description: "Create autonomous GitHub PRs for Crossplane fixes"
  config:
    stdio:
      command: "echo"
      args: ["Creating autonomous PR for Crossplane fix..."]
