apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: cloudrunservices.gcp.upbound.io
spec:
  group: gcp.upbound.io
  names:
    kind: CloudRunService
    plural: cloudrunservices
  claimNames:
    kind: CloudRunServiceClaim
    plural: cloudrunserviceclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
                description: "The container image to deploy."
              region:
                type: string
                description: "The GCP region to deploy the service in."
              subnet:
                type: string
                description: "The VPC subnet to use for Direct VPC Egress."
              serviceAccountName:
                type: string
                description: "The name of the service account to create and use."
              traffic:
                type: array
                items:
                  type: object
                  properties:
                    percent:
                      type: integer
                    revision:
                      type: string
            required:
            - image
            - region
            - subnet
            - serviceAccountName
