version: "3"

tasks:
  deploy:
    desc: "Run full infrastructure setup using Crossplane compositions"
    preconditions:
      - sh: test -n "$GKE_VPC"
        msg: "GKE_VPC is not set"
      - sh: test -n "$GKE_CONTROL_PLANE_CLUSTER"
        msg: "GKE_CONTROL_PLANE_CLUSTER is not set"
      - sh: test -n "$GKE_APPS_DEV_CLUSTER"
        msg: "GKE_APPS_DEV_CLUSTER is not set"
      - sh: test -n "$REGION"
        msg: "REGION is not set"
      - sh: test -n "$ZONE"
        msg: "ZONE is not set"
      - sh: test -n "$PROJECT_ID"
        msg: "PROJECT_ID is not set"
      - sh: test -n "$PROJECT_NUMBER"
        msg: "PROJECT_NUMBER is not set"
      - sh: test -n "$CONTROL_PLANE_SUBNET_NAME"
        msg: "CONTROL_PLANE_SUBNET_NAME is not set"
      - sh: test -n "$APPS_DEV_SUBNET_NAME"
        msg: "APPS_DEV_SUBNET_NAME is not set"
      - sh: test -n "$CROSSPLANE_GSA_KEY_FILE"
        msg: "CROSSPLANE_GSA_KEY_FILE is not set"
      - sh: test -n "$DOMAIN"
        msg: "DOMAIN is not set"
      - sh: test -n "$CERT_NAME"
        msg: "CERT_NAME is not set"
      - sh: test -n "$DNS_PROJECT"
        msg: "DNS_PROJECT is not set"
      - sh: test -n "$DNS_ZONE"
        msg: "DNS_ZONE is not set"
      - sh: test -n "$GITHUB_DEMO_REPO_OWNER"
        msg: "GITHUB_DEMO_REPO_OWNER is not set"
      - sh: test -n "$GITHUB_DEMO_REPO_NAME"
        msg: "GITHUB_DEMO_REPO_NAME is not set"
      - sh: test -n "$GITHUB_DEST_ORG_NAME"
        msg: "GITHUB_DEST_ORG_NAME is not set"
      - sh: test -n "$GITHUB_DEST_ORG_REPO_LVL_PAT"
        msg: "GITHUB_DEST_ORG_REPO_LVL_PAT is not set"
      - sh: test -n "$GITHUB_DEST_ORG_ORG_LVL_PAT"
        msg: "GITHUB_DEST_ORG_ORG_LVL_PAT is not set"
      - sh: test -n "$ANTHROPIC_API_KEY"
        msg: "ANTHROPIC_API_KEY is not set"
      - sh: test -n "$OPENAI_API_KEY"
        msg: "OPENAI_API_KEY is not set"
      - sh: test -n "$CLAUDE_MCP_CONFIG_FILE"
        msg: "CLAUDE_MCP_CONFIG_FILE is not set"
      - sh: test -n "$PINECONE_API_KEY"
        msg: "PINECONE_API_KEY is not set"
    env:
      GKE_VPC: "{{.GKE_VPC}}"
      GKE_CONTROL_PLANE_CLUSTER: "{{.GKE_CONTROL_PLANE_CLUSTER}}"
      GKE_APPS_DEV_CLUSTER: "{{.GKE_APPS_DEV_CLUSTER}}"
      REGION: "{{.REGION}}"
      ZONE: "{{.ZONE}}"
      PROJECT_ID: "{{.PROJECT_ID}}"
      PROJECT_NUMBER: "{{.PROJECT_NUMBER}}"
      CONTROL_PLANE_SUBNET_NAME: "{{.CONTROL_PLANE_SUBNET_NAME}}"
      APPS_DEV_SUBNET_NAME: "{{.APPS_DEV_SUBNET_NAME}}"
      CROSSPLANE_GSA_KEY_FILE: "{{.CROSSPLANE_GSA_KEY_FILE}}"
      DOMAIN: "{{.DOMAIN}}"
      CERT_NAME: "{{.CERT_NAME}}"
      DNS_PROJECT: "{{.DNS_PROJECT}}"
      DNS_ZONE: "{{.DNS_ZONE}}"
      GITHUB_DEMO_REPO_OWNER: "{{.GITHUB_DEMO_REPO_OWNER}}"
      GITHUB_DEMO_REPO_NAME: "{{.GITHUB_DEMO_REPO_NAME}}"
      GITHUB_DEST_ORG_NAME: "{{.GITHUB_DEST_ORG_NAME}}"
      GITHUB_DEST_ORG_REPO_LVL_PAT: "{{.GITHUB_DEST_ORG_REPO_LVL_PAT}}"
      GITHUB_DEST_ORG_ORG_LVL_PAT: "{{.GITHUB_DEST_ORG_ORG_LVL_PAT}}"
      ANTHROPIC_API_KEY: "{{.ANTHROPIC_API_KEY}}"
      OPENAI_API_KEY: "{{.OPENAI_API_KEY}}"
      CLAUDE_MCP_CONFIG_FILE: "{{.CLAUDE_MCP_CONFIG_FILE}}"
      PINECONE_API_KEY: "{{.PINECONE_API_KEY}}"
    cmds:
      - "{{.ROOT_DIR}}/bootstrap/scripts/setup-kind-cluster.sh"

  get-cluster-credentials:
    desc: "Get credentials for specified GKE cluster (usage: task debug:get-cluster-credentials CLUSTER=control-plane|apps-dev)"
    vars:
      CLUSTER: '{{.CLUSTER | default "control-plane"}}'
      ZONE: '{{default "australia-southeast1-a" .ZONE}}'
    requires:
      vars: [CLUSTER]
    cmds:
      - |
        if [[ "{{.CLUSTER}}" != "control-plane" && "{{.CLUSTER}}" != "apps-dev" ]]; then
          echo "❌ Error: CLUSTER must be either 'control-plane' or 'apps-dev'"
          echo "Usage: task debug:get-cluster-credentials CLUSTER=control-plane"
          echo "       task debug:get-cluster-credentials CLUSTER=apps-dev"
          exit 1
        fi
      - echo "🔑 Getting credentials for {{.CLUSTER}} cluster..."
      - gcloud container clusters get-credentials {{.CLUSTER}} --zone={{.ZONE}} --project={{.PROJECT_ID}}

  cleanup:
    desc: "Cleanup infrastructure (forcefull)"
    cmds:
      - "{{.ROOT_DIR}}/bootstrap/scripts/00-cleanup.sh"

  delete-kind:
    desc: "Delete kind cluster"
    cmds:
      - kind delete cluster --name kind-test-cluster
