version: "3"

tasks:
  deploy:
    desc: "Run full infrastructure setup using Crossplane compositions"
    cmds:
      - "{{.TASKFILE_DIR}}/infra-setup/02-create-and-setup-kind.sh"
      - "{{.TASKFILE_DIR}}/infra-setup/03-apply-compositions.sh"
      - "{{.TASKFILE_DIR}}/infra-setup/04-setup-gke-clusters.sh"
      - sleep 100
      - "{{.TASKFILE_DIR}}/infra-setup/98-argocd-gateway-api.sh"

  cleanup:
    desc: "Cleanup infrastructure (forcefull)"
    cmds:
      - "{{.TASKFILE_DIR}}/infra-setup/00-cleanup.sh"
