apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: ai
  source:
    repoURL: https://github.com/olga-mir/playground.git
    path: ai/kgateway/mcp-gateway
    targetRevision: develop
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
