apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-cmp-provider-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: platform
  source:
    repoURL: https://github.com/olga-mir/playground.git
    targetRevision: develop
    path: platform/crossplane/provider-configs
    plugin:
      name: env-substitution-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
