apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: platform
  sources:
    - repoURL: 'https://github.com/olga-mir/playground'
      targetRevision: develop
      path: platform/crossplane/functions
      directory:
        recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
