apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-core
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  path: ./kubernetes/namespaces/base/crossplane-system/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-config
