apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-compositions
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  path: ./kubernetes/components/crossplane-compositions/overlays/control-plane
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-config
  dependsOn:
    - name: crossplane-providerconfigs
    - name: crossplane-functions
