apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kagent-crds
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  path: ./kubernetes/namespaces/base/kagent/kagent/helm
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-config