apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters
  namespace: flux-system
  annotations:
    event.toolkit.fluxcd.io/cluster: "control-plane"
    event.toolkit.fluxcd.io/location: "australia-southeast1-a"
    event.toolkit.fluxcd.io/project: "${PROJECT_ID}"
spec:
  interval: 10m
  timeout: 30m
  path: ./kubernetes/namespaces/base/gkecluster-control-plane/clusters
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-config
  dependsOn:
    - name: crossplane-compositions
    - name: platform
