apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-providers
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  path: ./kubernetes/namespaces/base/crossplane-providers
  prune: true
  wait: true  # Wait for providers to be ready
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-config
  dependsOn:
    - name: crossplane-install  # Wait for Crossplane core to be installed first