apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-configs
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  path: ./kubernetes/namespaces/base/crossplane-configs
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-config
  dependsOn:
    - name: crossplane-providers  # Wait for providers to install and create CRDs