---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  path: kubernetes/namespaces/overlays/kind
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system