apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  # Note: Crossplane components are installed via separate staged kustomizations
  # in crossplane-source.yaml to ensure proper installation order