# Applications to be deployed on control-plane cluster via Flux
apiVersion: v1
kind: Namespace
metadata:
  name: kagent-system
---
# AI platform API Key secret for kagent
#apiVersion: v1
#kind: Secret
#metadata:
#  name: kagent-anthropic
#  namespace: kagent-system
#type: Opaque
#data:
#  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY_B64}  # Base64 encoded in CI
---
# TODO - to implement in the next stage
# apiVersion: v1
# kind: Secret
# metadata:
#   name: kagent-openai
#   namespace: kagent-system
# type: Opaque
# data:
#   OPENAI_API_KEY: ${OPENAI_API_KEY_B64}  # Base64 encoded in CI
# ---
# Gateway API CRDs (if not already installed)
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.3.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: "./config/crd/experimental"
  prune: true
