apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-functions
  namespace: flux-system
spec:
  interval: 10m
  path: "./bootstrap/kind/crossplane/base/functions"
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-config
  dependsOn:
    - name: crossplane-install