apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gke-cluster-compositions
  namespace: flux-system
spec:
  interval: 10m
  path: "./bootstrap/kind/crossplane/compositions"
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-config
  dependsOn:
    - name: crossplane-functions