apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: gke-mgmt-cluster-k8s-config # ProviderConfig for Kind's Crossplane to manage GKE Mgmt Cluster
spec:
  credentials:
    source: Secret
    secretRef:
      # This secret is in the Kind cluster, created when GKE_MGMT_CLUSTER was provisioned.
      # It's specified in mgmt-cluster.yaml.tpl's writeConnectionSecretToRef.
      namespace: crossplane-system # Assuming this is the namespace in Kind
      name: ${GKE_MGMT_CLUSTER}-kubeconfig # Ensure this matches the output of your GKE cluster resource
      key: kubeconfig
