apiVersion: platform.example.com/v1alpha1
kind: GKECluster
metadata:
  name: mgmt-cluster-example
  namespace: default
spec:
  parameters:
    clusterName: gke-mgmt-cluster
    clusterType: mgmt
    projectId: "${PROJECT_ID}"
    region: "${REGION}"
    zone: "${ZONE}"
    vpcName: "${GKE_VPC}"
    subnetName: "${MGMT_SUBNET_NAME}"
    machineType: "e2-standard-4"
    minNodes: 2
    maxNodes: 5
    
    # ArgoCD configuration
    argocd:
      enabled: true
      version: "v2.14.10"
      chartVersion: "7.8.26"
      repoUrl: "https://github.com/${GITHUB_DEMO_REPO_OWNER}/${GITHUB_DEMO_REPO_NAME}.git"
      repoToken: "${GITHUB_DEMO_REPO_PAT}"
      repoOwner: "${GITHUB_DEMO_REPO_OWNER}"
    
    # Crossplane configuration
    crossplane:
      enabled: true
      version: "v2.0.0-preview.1"
  
  compositeDeletePolicy: Foreground
  writeConnectionSecretsToNamespace: crossplane-system