apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: claude-model-config
  namespace: kagent-system
spec:
  apiKeySecret: kagent-anthropic
  apiKeySecretKey: KAGENT_ANTHROPIC_API_KEY
  model: claude-sonnet-4-6
  provider: Anthropic
  anthropic: {}
