apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: team-charlie-environment
  labels:
    team: team-charlie
data:
  # Team-specific repository defaults
  team: "team-charlie"
  requiredApprovingReviewCount: 12 # something rediculous for demo
  defaultWebhookUrl: "https://charlie-team.company.com/webhook"
  serviceTier: "standard"
  requireSignedCommits: "true"

  # Team-specific variables that should be applied to all repos
  teamVariables:
    TEAM_NAME: "team-charlie" 
    ENVIRONMENT: "production"
    SERVICE_TIER: "standard"
