applications:
  - name: crossplane-platform-apis
    namespace: crossplane-system
    syncWave: "4"
    project: platform
    sources:
      - path: platform/crossplane/definitions
      - path: platform/crossplane/compositions
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - SkipDryRunOnMissingResource=true
