apiVersion: platform.tornado-demo.io/v1alpha1
kind: TornadoRepo
metadata:
  name: team-charlie-service-xyz
  namespace: team-charlie
spec:
  serviceName: service-xyz
  teamName: team-charlie
  description: "Secondary service for analytics and reporting"
  visibility: private

  settings:
    defaultBranch: main
    allowRebaseMerge: false
    deleteBranchOnMerge: true

  security:
    secretScanning: true
    secretScanningPushProtection: true
    dependabotAlerts: true
    dependabotSecurityUpdates: true

  branchProtection:
    customRulesets:
    - name: "main-protection"
      target: "branch"
      enforcement: "active"
      conditions:
        refName:
          include: ["refs/heads/main"]
      rules:
      - type: "required_status_checks"
        parameters:
          requiredStatusChecks:
          - context: "ci/build"
          - context: "ci/test"
          strictRequired: true
      - type: "required_pull_request_reviews"
        parameters:
          requiredApprovingReviewCount: 2
          dismissStaleReviews: true
          requireCodeOwnerReviews: true

  variables:
  - name: "ENVIRONMENT"
    value: "production"
  - name: "SERVICE_TIER"
    value: "standard"

  actions:
    enabled: true
    allowedActions: "selected"
    selectedActionsConfig:
      githubOwnedAllowed: true
      verifiedAllowed: true
      patternsAllowed:
      - "actions/checkout@*"
      - "actions/setup-*"

  teamAccess:
  - team: charlie
    permission: maintain
  - team: platform
    permission: admin

  compliance:
    codeowners:
      enabled: true
      content: |
        # Global owners
        * @myorg/team-charlie @myorg/platform

        # Analytics and reporting paths
        /src/analytics/ @myorg/team-charlie
        /src/reports/ @myorg/team-charlie

        # Infrastructure
        /k8s/ @myorg/platform
        /.github/ @myorg/platform