---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-dispatch
  namespace: flux-system
spec:
  type: githubdispatch
  address: https://github.com/olga-mir/playground
  secretRef:
    name: github-webhook-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-dispatch-cluster-created
  namespace: flux-system
spec:
  providerRef:
    name: github-dispatch
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: clusters
      namespace: flux-system
  inclusionList:
    - "GKECluster"

  # Dynamic metadata now comes from event.toolkit.fluxcd.io/ annotations on Kustomizations
  # No static eventMetadata needed - RFC-0008 handles this automatically
