apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-test
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: playground-repo
  path: "./flux-test"
  prune: true