apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cloudrunservices.gcp.upbound.io
  labels:
    provider: gcp
    gcp.upbound.io/cloudrun-service: "true"
spec:
  compositeTypeRef:
    apiVersion: platform.tornado-demo.io/v1alpha1
    kind: CloudRunService
  patchSets:
  - name: common-metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: cloudrun-service-sa
    base:
      apiVersion: iam.gcp.upbound.io/v1beta1
      kind: ServiceAccount
      metadata:
        labels:
          gcp.upbound.io/cloudrun-service: "true"
    patches:
    - fromFieldPath: "spec.serviceAccountName"
      toFieldPath: "metadata.name"

  - name: cloudrun-service
    base:
      apiVersion: cloudrun.gcp.upbound.io/v1beta1
      kind: V2Service
      metadata:
        labels:
          gcp.upbound.io/cloudrun-service: "true"
      spec:
        forProvider:
          template:
            containers:
            - image: ""
            serviceAccountNameSelector:
              matchControllerRef: true
            vpcAccess:
              networkInterfaces:
              - subnetwork: ""
              egress: ""
          traffic: []
    patches:
    - fromFieldPath: "spec.image"
      toFieldPath: "spec.forProvider.template.containers[0].image"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
    - fromFieldPath: "metadata.name"
      toFieldPath: "metadata.name"
    - fromFieldPath: "spec.traffic"
      toFieldPath: "spec.forProvider.traffic"
    - fromFieldPath: "spec.vpcAccess.egress"
      toFieldPath: "spec.forProvider.template.vpcAccess.egress"
    - fromFieldPath: "spec.vpcAccess.networkInterfaces[0].subnetwork"
      toFieldPath: "spec.forProvider.template.vpcAccess.networkInterfaces[0].subnetwork"

  - name: cloudrun-invoker-binding
    base:
      apiVersion: cloudrun.gcp.upbound.io/v1beta1
      kind: V2ServiceIamPolicy
      spec:
        forProvider:
          policyData: |
            {
              "bindings": [
                {
                  "role": "roles/run.invoker",
                  "members": [
                    "allUsers"
                  ]
                }
              ]
            }
          serviceSelector:
            matchControllerRef: true
    patches:
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
