apiVersion: gcp.upbound.io/v1alpha1
kind: CloudRunServiceClaim
metadata:
  name: fortio-cloudrun-service
  namespace: default
spec:
  compositionRef:
    name: cloudrunservice.gcp.upbound.io
  parameters:
    image: fortio/fortio:latest
    region: australia-southeast1
    serviceAccountName: fortio-cloudrun-sa
    vpcAccess:
      connector: projects/${PROJECT_ID}/locations/australia-southeast1/connectors/cloudrun-vpc-connector
      egress: all-traffic
    traffic:
    - percent: 50
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    - percent: 50
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_REVISION"
      revision: "fortio-cloudrun-service-66cbf9b79f"
