apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: teamconfigs.platform.tornado-demo.io
spec:
  group: platform.tornado-demo.io
  names:
    kind: TeamConfig
    plural: teamconfigs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                teamName:
                  type: string
                description:
                  type: string
                privacy:
                  type: string
                  enum: [secret, closed]
                teamMaintainerUsername:
                  type: string
                  description: "The GitHub username of the primary maintainer for this team."
                parentTeam:
                  type: string
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      username:
                        type: string
                      role:
                        type: string
                        enum: [member, maintainer]
                repositoryAccess:
                  type: array
                  items:
                    type: object
                    properties:
                      repositoryName:
                        type: string
                      permission:
                        type: string
                        enum: [pull, push, maintain, triage, admin]
