apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: organizationconfigs.platform.tornado-demo.io
spec:
  group: platform.tornado-demo.io
  names:
    kind: OrganizationConfig
    plural: organizationconfigs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                organizationName:
                  type: string
                  description: "GitHub organization name"
                securitySettings:
                  type: object
                  properties:
                    advancedSecurityEnabled:
                      type: boolean
                    dependabotAlertsEnabled:
                      type: boolean
                    dependabotSecurityUpdatesEnabled:
                      type: boolean
                    secretScanningEnabled:
                      type: boolean
                organizationRulesets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      enforcement:
                        type: string
                        enum: [active, evaluate, disabled]
                      rules:
                        type: object
                defaultTeams:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      privacy:
                        type: string
                        enum: [secret, closed]
