apiVersion: apiextensions.crossplane.io/v2alpha1
kind: CompositeResourceDefinition
metadata:
  name: valuestreamlandingzones.platform.tornado-demo.io
spec:
  group: platform.tornado-demo.io
  names:
    kind: ValueStreamLandingZone
    plural: valuestreamlandingzones
    singular: valuestreamlandingzone
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - environment
                - teamName
                - serviceId
              properties:
                environment:
                  type: string
                  enum: ["dev", "stage", "prod"]
                teamName:
                  type: string
                serviceId:
                  type: string
                githubConfig:
                  type: object
                  properties:
                    repositoryVisibility:
                      type: string
                      enum: ["private", "public"]
                    useTemplate:
                      type: boolean
                    enableActions:
                      type: boolean
                    teamPermission:
                      type: string
                      enum: ["pull", "triage", "push", "maintain", "admin"]
                networkTags:
                  type: array
                  items:
                    type: string
                gcpServices:
                  type: array
                  items:
                    type: string
                workloadIdentity:
                  type: object
                  properties:
                    roles:
                      type: array
                      items:
                        type: string
                writeConnectionSecretToRef:
                  type: object
                  required:
                    - name
                    - namespace
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
            status:
              type: object
              properties:
                projectId:
                  type: string
                  description: "The generated GCP project ID"
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
