apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: teamconfigs.github.yourdomain.com
spec:
  compositeTypeRef:
    apiVersion: github.yourdomain.com/v1alpha1
    kind: TeamConfig
  mode: Pipeline
  pipeline:
    - step: create-team
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: team
            base:
              apiVersion: team.github.upbound.io/v1alpha1
              kind: Team
              metadata:
                name: team-name
              spec:
                forProvider:
                  privacy: closed
                  description: Team created by Crossplane
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.description
                toFieldPath: spec.forProvider.description
              - type: FromCompositeFieldPath
                fromFieldPath: spec.privacy
                toFieldPath: spec.forProvider.privacy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parentTeam
                toFieldPath: spec.forProvider.parentTeamId
                policy:
                  fromFieldPath: Optional

    - step: add-team-members
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: team-membership
            base:
              apiVersion: team.github.upbound.io/v1alpha1
              kind: TeamMembership
              metadata:
                name: team-member
              spec:
                forProvider:
                  role: member
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.members[0].username
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.members[0].username
                toFieldPath: spec.forProvider.username
              - type: FromCompositeFieldPath
                fromFieldPath: spec.members[0].role
                toFieldPath: spec.forProvider.role
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: spec.forProvider.teamId

    - step: configure-repository-access
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: team-repository
            base:
              apiVersion: team.github.upbound.io/v1alpha1
              kind: TeamRepository
              metadata:
                name: team-repo-access
              spec:
                forProvider:
                  permission: push
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.repositoryAccess[0].repositoryName
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "%s-%s"
                      type: Format
                      variables:
                        - fromFieldPath: spec.teamName
                        - fromFieldPath: spec.repositoryAccess[0].repositoryName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.repositoryAccess[0].repositoryName
                toFieldPath: spec.forProvider.repository
              - type: FromCompositeFieldPath
                fromFieldPath: spec.repositoryAccess[0].permission
                toFieldPath: spec.forProvider.permission
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: spec.forProvider.teamId:w
