apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: organizationconfigs.platform.tornado-demo.io
spec:
  compositeTypeRef:
    apiVersion: platform.tornado-demo.io/v1alpha1
    kind: OrganizationConfig
  mode: Pipeline
  pipeline:
    - step: create-organization-ruleset
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: organization-ruleset
            base:
              apiVersion: organization.github.upbound.io/v1alpha1
              kind: OrganizationRuleset
              metadata:
                name: default-branch-protection-ruleset
              spec:
                forProvider:
                  enforcement: active
                  target: branch
                  name: Default Branch Protection
                  conditions:
                    refName:
                      include:
                        - "~ALL"
                  rules:
                    pullRequest:
                      requiredApprovingReviewCount: 1
                      requireCodeOwnerReview: true
                      requiredReviewThreadResolution: true
                providerConfigRef:
                  name: github-provider-org-lvl
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.organizationRulesets[0].name
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.organizationRulesets[0].name
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.organizationRulesets[0].enforcement
                toFieldPath: spec.forProvider.enforcement

    # Repository access level based on repo labels
    - step: configure-actions-access-levels
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: prod-critical-repo-actions-policy
            base:
              apiVersion: actions.github.upbound.io/v1alpha1
              kind: RepositoryAccessLevel
              metadata:
                name: prod-critical-verified-actions-policy
              spec:
                forProvider:
                  accessLevel: "selected"
                  selectedActionsConfig:
                    githubOwnedAllowed: true # Recommended to allow GitHub's own actions (e.g., actions/checkout)
                    verifiedAllowed: true    # Allows actions from verified creators
                    # patternsAllowed: []    # Optionally, specify specific action patterns. Empty means only the above are allowed.
                  repositorySelector:
                    matchLabels:
                      "production-critical": "true"
                providerConfigRef:
                  name: github-provider-org-lvl
