apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: teamconfigs.platform.tornado-demo.io
spec:
  compositeTypeRef:
    apiVersion: platform.tornado-demo.io/v1alpha1
    kind: TeamConfig
  mode: Pipeline
  pipeline:
    - step: create-team
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: team
            base:
              apiVersion: team.github.upbound.io/v1alpha1
              kind: Team
              metadata:
                name: team-name
              spec:
                forProvider:
                  privacy: closed
                  description: Team created by Crossplane
                providerConfigRef:
                  name: github-provider-org
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.description
                toFieldPath: spec.forProvider.description
              - type: FromCompositeFieldPath
                fromFieldPath: spec.privacy
                toFieldPath: spec.forProvider.privacy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parentTeam
                toFieldPath: spec.forProvider.parentTeamId
                policy:
                  fromFieldPath: Optional

    - step: configure-repository-access
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: team-repository
            base:
              apiVersion: team.github.upbound.io/v1alpha1
              kind: TeamRepository
              metadata:
                name: team-repo-access
              spec:
                forProvider:
                  permission: push
                providerConfigRef:
                  name: github-provider-org
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.teamName
                    - fromFieldPath: spec.repositoryAccess[0].repositoryName
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.repositoryAccess[0].repositoryName
                toFieldPath: spec.forProvider.repository
              - type: FromCompositeFieldPath
                fromFieldPath: spec.repositoryAccess[0].permission
                toFieldPath: spec.forProvider.permission
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: spec.forProvider.teamId

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
