apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespace.yaml  # Ensure namespace exists first
  - kgateway-helm-repo.yaml
  - kgateway-crds-release.yaml
  - kgateway-release.yaml