apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: experiment-ebpf
  namespace: flux-system
spec:
  image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/experiment-ebpf/experiment-ebpf
  provider: gcp
  interval: 1m
