apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github-provider-org
  annotations:
    todo-cmp-workaround: ${PROJECT_ID}
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-provider-secret-org
      namespace: crossplane-system
      key: credentials
