apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: cloudRunServices.platform.tornado-demo.io
  labels:
    provider: gcp
    service: cloudrun
spec:
  group: platform.tornado-demo.io
  names:
    kind: CloudRunService
    plural: cloudrunservices
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  # Service configuration
                  name:
                    type: string
                    description: "Name of the Cloud Run service"
                  image:
                    type: string
                    description: "Container image to deploy"
                    default: "fortio/fortio:latest"
                  region:
                    type: string
                    description: "GCP region for deployment"
                    default: "australia-southeast1"

                  # Networking configuration
                  network:
                    type: string
                    description: "VPC for Direct VPC Egress"

                  subnetName:
                    type: string
                    description: "VPC subnet for Direct VPC Egress"

                  # Authentication and IAM
                  allowUnauthenticated:
                    type: boolean
                    description: "Allow unauthenticated access"
                    default: true

                  # Traffic configuration for blue-green deployments
                  traffic:
                    type: object
                    properties:
                      latestRevision:
                        type: boolean
                        description: "Route traffic to latest revision"
                        default: true
                      percent:
                        type: integer
                        description: "Percentage of traffic to route"
                        default: 100
                        minimum: 0
                        maximum: 100
                    default:
                      latestRevision: true
                      percent: 100

                  # Container configuration
                  containerConfig:
                    type: object
                    properties:
                      port:
                        type: integer
                        description: "Container port"
                        default: 8080
                      env:
                        type: array
                        description: "Environment variables"
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                        default: []
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                                default: "1000m"
                              memory:
                                type: string
                                default: "512Mi"
                        default:
                          limits:
                            cpu: "1000m"
                            memory: "512Mi"
                    default:
                      port: 8080
                      env: []
                      resources:
                        limits:
                          cpu: "1000m"
                          memory: "512Mi"

                  # Service Account
                  serviceAccount:
                    type: object
                    properties:
                      create:
                        type: boolean
                        description: "Create dedicated service account"
                        default: true
                      name:
                        type: string
                        description: "Service account name (auto-generated if not provided)"
                    default:
                      create: true

                required:
                - name
                - network
                - subnetName
            required:
            - parameters
          status:
            type: object
            properties:
              # Output service information
              serviceUrl:
                type: string
                description: "URL of the deployed Cloud Run service"
              serviceAccount:
                type: string
                description: "Service account email"
              ready:
                type: boolean
                description: "Service deployment status"
  claimNames:
    kind: CloudRunService
    plural: cloudrunservices
