apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kind cluster overlay - flux system with staged Crossplane installation
# Note: Crossplane components (install, providers, compositions) are managed
# by the staged Flux Kustomizations in flux-system/crossplane-source.yaml
resources:
  - ../../base/flux-system