name: kagent
chart: kagent
repoURL: ghcr.io/kagent-dev/kagent/helm
targetRevision: 0.3.11
namespace: kagent-system
syncWave: "1"
project: ai
helm:
  values: |
    controller:
      loglevel: "debug"
    providers:
      default: OpenAI
      openAI:
        provider: openAI
        model: "gpt-4.1-mini"
        apiKeySecretRef: false
        apiKey: false
        config: {}
