project: ai
syncWave: "2"

name: kagent
chart: kagent
repoURL: ghcr.io/kagent-dev/kagent/helm
targetRevision: 0.3.15
namespace: kagent-system
helm:
  values:
    providers:
      default: openAI
      openAI:
        provider: OpenAI
        model: "gpt-4.1-mini"
        apiKeySecretRef: kagent-openai
        apiKeySecretKey: OPENAI_API_KEY
        config: {}
