applications:
  - name: kgateway-crds
    chart: kgateway-crds
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.1.0-main
    namespace: kgateway-system
    syncWave: "0"
    project: ai
  - name: kgateway
    chart: kgateway
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.1.0-main
    namespace: kgateway-system
    syncWave: "1"
    project: ai
