project: ai
syncWave: "1"

name: kgateway
chart: kgateway
repoURL: cr.kgateway.dev/kgateway-dev/charts
targetRevision: v2.0.3
namespace: kgateway-system
helm:
  values:
    agentGateway:
      enabled: true
    image:
      registry: ghcr.io/kgateway-dev
    discoveryNamespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: kgateway-system
