project: ai
syncWave: "1"

name: kgateway-ai
chart: kgateway
repoURL: us-docker.pkg.dev/developers-369321/gloo-platform-dev/charts
targetRevision: v2.1.0-main
namespace: kgateway-system
helm:
  values:
    agentGateway:
      enabled: true
    gateway:
      aiExtension:
        enabled: true
        # I don't understand agentGateway vs aiExtention
        # https://kgateway.dev/docs/ai/setup/
