apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubefed
  namespace: kubefed
spec:
  interval: 5m
  chart:
    spec:
      chart: kubefed
      version: '0.9.2'
      sourceRef:
        kind: HelmRepository
        name: kubefed
        namespace: flux-system
      interval: 1m
  values:
    controllermanager:
      controller: 
        replicaCount: 2
