apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Control-plane cluster overlay - platform services only
# GKE cluster resources are handled by the clusters kustomization
resources:
  # Install Crossplane on control-plane cluster for workload cluster provisioning
  - ../../base/crossplane-system
  - ../../base/platform-services
  - ../../base/kagent
  - ../../base/kagent-system
  - ../../base/kgateway-system
