#!/usr/bin/env bash
# fetch-latest-versions.sh — Reads scan-versions.sh JSON from stdin,
# fetches latest versions, and writes a markdown report to stdout.
#
# For Helm charts with HTTP repos: fetches index.yaml directly (no auth needed).
# For OCI/GitHub-based components: uses gh CLI (GITHUB_TOKEN or gh auth login).
#
# Usage: scan-versions.sh | fetch-latest-versions.sh > .version-report.md

set -euo pipefail

input=$(cat)
date_str=$(date -u +%Y-%m-%d)

info() { echo "INFO:  $*" >&2; }
warn() { echo "WARN:  $*" >&2; }

# ── Collect unique sources to fetch ──────────────────────────────────────────
declare -A github_latest   # repo → latest tag
declare -A helm_latest     # "URL|CHART" → latest version

fetch_github() {
  local repo="$1"
  [[ -n "${github_latest[$repo]+_}" ]] && return  # already fetched

  # Pipe through jq explicitly so 404 bodies (no .tag_name) yield empty string
  # rather than the raw error JSON leaking into the "latest" field.
  local body
  body=$(gh api "repos/${repo}/releases/latest" 2>/dev/null || true)
  tag=$(echo "$body" | jq -r '.tag_name // empty' 2>/dev/null || true)

  if [[ -z "$tag" ]]; then
    body=$(gh api "repos/${repo}/tags" 2>/dev/null || true)
    tag=$(echo "$body" | jq -r '.[0].name // empty' 2>/dev/null || true)
  fi

  if [[ -z "$tag" ]]; then
    warn "No releases or tags found for ${repo} (repo may not exist or have no releases)"
  fi
  github_latest["$repo"]="${tag:-unknown}"
  info "github ${repo} → ${github_latest[$repo]}"
}

fetch_helm_index() {
  local url="$1" chart="$2" key="${1}|${2}"
  [[ -n "${helm_latest[$key]+_}" ]] && return  # already fetched

  # Fetch the Helm repo index and extract the latest version for this chart.
  # sort -V handles semver correctly (including pre-release like 2.0.0-rc.1).
  latest=$(curl -sL "${url%/}/index.yaml" \
    | yq -r ".entries.\"${chart}\"[].version" 2>/dev/null \
    | sort -V | tail -1 || true)
  helm_latest["$key"]="${latest:-unknown}"
  info "helm   ${url} / ${chart} → ${helm_latest[$key]}"
}

# Pre-fetch all unique sources
while IFS= read -r item; do
  src_type=$(echo "$item" | jq -r '.source.type')
  if [[ "$src_type" == "github" ]]; then
    repo=$(echo "$item" | jq -r '.source.repo')
    fetch_github "$repo"
  elif [[ "$src_type" == "helm_index" ]]; then
    url=$(  echo "$item" | jq -r '.source.url')
    chart=$(echo "$item" | jq -r '.source.chart')
    fetch_helm_index "$url" "$chart"
  fi
done < <(echo "$input" | jq -c '.[]')

# ── Build enriched JSON ───────────────────────────────────────────────────────
enriched="[]"
while IFS= read -r item; do
  src_type=$(echo "$item" | jq -r '.source.type')
  cur=$(echo "$item" | jq -r '.current_version')

  if [[ "$src_type" == "github" ]]; then
    repo=$(echo "$item" | jq -r '.source.repo')
    latest="${github_latest[$repo]:-unknown}"
  else
    url=$(  echo "$item" | jq -r '.source.url')
    chart=$(echo "$item" | jq -r '.source.chart')
    latest="${helm_latest["${url}|${chart}"]:-unknown}"
  fi

  # Compare versions, stripping v prefix
  cur_v="${cur#v}"; cur_v="${cur_v#litmus-}"
  lat_v="${latest#v}"; lat_v="${lat_v#litmus-}"
  needs=$( [[ "$latest" != "unknown" && "$cur_v" != "$lat_v" ]] && echo "true" || echo "false" )

  enriched=$(echo "$enriched" | jq \
    --argjson item "$item" \
    --arg latest "$latest" \
    --argjson needs "$needs" \
    '. + [$item + {latest_version: $latest, needs_update: $needs}]')
done < <(echo "$input" | jq -c '.[]')

# ── Write markdown report ─────────────────────────────────────────────────────
cat <<EOF
# Version Update Report — ${date_str}

Generated by \`scan-versions.sh | fetch-latest-versions.sh\`.

## Results

| Component | Type | File | Current | Latest | Update? |
|-----------|------|------|---------|--------|---------|
EOF

echo "$enriched" | jq -r '.[] |
  "| \(.component) | \(.type) | \(.file) | \(.current_version) | \(.latest_version) | \(if .needs_update then "**YES**" else "no" end) |"'

total=$(echo "$enriched" | jq '[.[] | select(.needs_update)] | length')
echo ""
echo "${total} component(s) need updating."

# Also write the enriched JSON for potential downstream use
echo "$enriched" > .version-report.json
