apiVersion: platform.tornado-demo.io/v1alpha1
kind: GKECluster
metadata:
  name: apps-dev-cluster
  namespace: apps-dev
spec:
  parameters:
    clusterName: "${GKE_APPS_DEV_CLUSTER}"
    clusterType: workload
    projectId: "${PROJECT_ID}"
    region: "${REGION}"
    zone: "${ZONE}"
    vpcName: "${GKE_VPC}"
    subnetName: "${APPS_DEV_SUBNET_NAME}"
    machineType: "e2-highcpu-4"
    minNodes: 2
    maxNodes: 6
    nodePools:
      - name: noisy-node
        machineType: "e2-standard-2"
        minNodes: 1
        maxNodes: 1
        labels:
          workload: noisy-node
        taints:
          - key: dedicated
            value: noisy-node
            effect: NO_SCHEDULE
      - name: gvisor-sandbox
        machineType: "e2-standard-2"
        minNodes: 1
        maxNodes: 2
        # gVisor requires cos_containerd image type
        imageType: "cos_containerd"
        sandboxConfig:
          type: gvisor
        labels:
          sandbox: gvisor
        taints:
          - key: sandbox.gke.io/runtime
            value: gvisor
            effect: NO_SCHEDULE

