apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/olga-mir/playground
          revision: develop
          files:
          - path: "platform/config/repository.yaml"
          pathParamPrefix: repo
      - git:
          repoURL: https://github.com/olga-mir/playground
          revision: develop
          files:
          - path: "platform/config/helm-applications/*.yaml"
          pathParamPrefix: apps
  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
    spec:
      project: '{{ .project }}'
      source:
        chart: '{{ .chart }}'
        repoURL: '{{ .repoURL }}'
        targetRevision: '{{ .targetRevision }}'
        helm:
          values: |-
            {{- with .helm.values }}
            {{ toYaml . }}
            {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - FailOnSharedResource=true
