apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: teams-tenancies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
  - git:
      repoURL: 'https://github.com/olga-mir/playground'
      revision: develop-cloud-run-claude
      directories:
      - path: 'teams/*'
  template:
    metadata:
      name: '{{ path.basename }}-tenant'
      namespace: argocd
      labels:
        team: '{{ path.basename }}'
    spec:
      project: tenants
      source:
        repoURL: 'https://github.com/olga-mir/playground'
        targetRevision: develop-cloud-run-claude
        path: '{{ path }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ path.basename }}-tenant'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
