apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: workload-cluster-composition
  labels:
    provider: gcp
    service: workload-cluster
spec:
  compositeTypeRef:
    apiVersion: platform.tornado-demo.io/v1alpha1
    kind: WorkloadCluster

  mode: Pipeline
  pipeline:
  - step: cluster-infrastructure
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          # GKE Cluster
          apiVersion: container.gcp-beta.upbound.io/v1beta2
          kind: Cluster
          metadata:
            name: {{ .observed.composite.resource.spec.parameters.clusterName }}
            annotations:
              crossplane.io/external-name: {{ .observed.composite.resource.spec.parameters.clusterName }}
              gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.spec.parameters.clusterName }}
          spec:
            forProvider:
              network: "projects/{{ .observed.composite.resource.spec.parameters.projectId }}/global/networks/{{ .observed.composite.resource.spec.parameters.vpcName }}"
              subnetwork: "projects/{{ .observed.composite.resource.spec.parameters.projectId }}/regions/{{ .observed.composite.resource.spec.parameters.region }}/subnetworks/{{ .observed.composite.resource.spec.parameters.subnetName }}"
              location: "{{ .observed.composite.resource.spec.parameters.zone }}"
              workloadIdentityConfig:
                workloadPool: "{{ .observed.composite.resource.spec.parameters.projectId }}.svc.id.goog"
              initialNodeCount: 1
              removeDefaultNodePool: true
              gatewayApiConfig:
                channel: CHANNEL_STANDARD
              enableAutopilot: false
              releaseChannel:
                channel: RAPID
            writeConnectionSecretToRef:
              namespace: crossplane-system
              name: {{ .observed.composite.resource.spec.parameters.clusterName }}-kubeconfig
          ---
          # GKE Node Pool
          apiVersion: container.gcp-beta.upbound.io/v1beta2
          kind: NodePool
          metadata:
            name: {{ .observed.composite.resource.spec.parameters.clusterName }}-pool
            annotations:
              crossplane.io/external-name: {{ .observed.composite.resource.spec.parameters.clusterName }}-pool
              gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.spec.parameters.clusterName }}-pool
          spec:
            forProvider:
              clusterRef:
                name: {{ .observed.composite.resource.spec.parameters.clusterName }}
              maxPodsPerNode: 32
              nodeConfig:
                spot: true
                machineType: {{ .observed.composite.resource.spec.parameters.machineType }}
                diskSizeGb: 50
              autoscaling:
                minNodeCount: {{ .observed.composite.resource.spec.parameters.minNodes }}
                maxNodeCount: {{ .observed.composite.resource.spec.parameters.maxNodes }}
              management:
                autoRepair: true
                autoUpgrade: true


  - step: ready
    functionRef:
      name: function-auto-ready
