apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Include the existing control-plane resources that were scattered
  - ../crossplane-install.yaml
  - ../crossplane-functions.yaml
  - ../gke-cluster-compositions.yaml
  - ../apps-dev-flux-kustomization.yaml
  - ../apps-dev-alert.yaml