#!/usr/bin/env bash
# fetch-latest-versions.sh — Reads scan-versions.sh JSON from stdin,
# fetches latest GitHub releases, and writes a markdown report to stdout.
#
# Requires: gh CLI authenticated (GITHUB_TOKEN or gh auth login)
# Usage: scan-versions.sh | fetch-latest-versions.sh > .version-report.md

set -euo pipefail

input=$(cat)
date_str=$(date -u +%Y-%m-%d)

info()  { echo "INFO:  $*" >&2; }
warn()  { echo "WARN:  $*" >&2; }

# ── Fetch latest tag for each unique GitHub repo ──────────────────────────────
declare -A latest_tags

while IFS= read -r repo; do
  [[ -z "$repo" ]] && continue
  info "Fetching latest release for ${repo} ..."

  tag=$(gh api "repos/${repo}/releases/latest" --jq '.tag_name' 2>/dev/null || true)
  if [[ -z "$tag" ]]; then
    # Fall back to latest tag (some repos don't use releases)
    tag=$(gh api "repos/${repo}/tags" --jq '.[0].name' 2>/dev/null || true)
  fi

  if [[ -z "$tag" ]]; then
    warn "Could not fetch latest version for ${repo}"
    latest_tags["$repo"]="unknown"
  else
    latest_tags["$repo"]="$tag"
    info "  → ${tag}"
  fi
done < <(echo "$input" | jq -r '.[].github_repo' | sort -u)

# ── Build the latest_map as a JSON object for jq ─────────────────────────────
latest_json="{}"
for repo in "${!latest_tags[@]}"; do
  latest_json=$(echo "$latest_json" \
    | jq --arg k "$repo" --arg v "${latest_tags[$repo]}" '.[$k] = $v')
done

# ── Join input with latest versions ──────────────────────────────────────────
enriched=$(echo "$input" | jq \
  --argjson latest "$latest_json" \
  'map(
    . + {
      latest_version: ($latest[.github_repo] // "unknown"),
      needs_update: (
        ($latest[.github_repo] // "unknown") != "unknown" and
        ((.current_version | ltrimstr("v")) != (($latest[.github_repo] // "") | ltrimstr("v")))
      )
    }
  )')

# ── Write markdown report ─────────────────────────────────────────────────────
cat <<EOF
# Version Update Report — ${date_str}

Generated by \`bootstrap/scripts/scan-versions.sh | fetch-latest-versions.sh\`.

## Results

| Component | Type | File | Current | Latest | Update? |
|-----------|------|------|---------|--------|---------|
EOF

echo "$enriched" | jq -r '.[] |
  "| \(.component) | \(.type) | \(.file) | \(.current_version) | \(.latest_version) | \(if .needs_update then "**YES**" else "no" end) |"'

# Summary counts
total=$(echo "$enriched" | jq '[.[] | select(.needs_update)] | length')
echo ""
echo "${total} component(s) need updating."

# Also write the enriched JSON for any downstream tooling
echo "$enriched" > .version-report.json
