# https://kagent.dev/docs/getting-started/first-mcp-tool
# Current example excludes Agent resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-website-fetcher
  namespace: kagent
  labels:
    app: mcp-website-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-website-fetcher
  template:
    metadata:
      labels:
        app: mcp-website-fetcher
    spec:
      containers:
        - name: mcp-website-fetcher
          image: ghcr.io/peterj/mcp-website-fetcher:sha-d2db5b3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /sse
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-website-fetcher
  namespace: kagent
  annotations:
    kagent.dev/tool.type: "mcp"
spec:
  selector:
    app: mcp-website-fetcher
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-toolserver
  namespace: kagent
spec:
  description: Fetches a website and returns its content
  config:
    sse:
      url: http://mcp-website-fetcher.kagent.svc.cluster.local/sse
