name: Crossplane Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'control-plane-crossplane/compositions/**/*.yaml'
      - 'control-plane-crossplane/compositions/**/*.xrd.yaml'
      - 'control-plane-crossplane/compositions/**/*.workload-cluster-composition.yaml'
      - 'control-plane-crossplane/compositions/**/*.workload-cluster-xrd.yaml'

jobs:
  install-crossplane-cli:
    runs-on: ubuntu-latest
    outputs:
      crossplane-cli-path: ${{ steps.install.outputs.crossplane-cli-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Crossplane CLI
        id: install
        run: |
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | bash
          echo "crossplane-cli-path=$(which crossplane)" >> $GITHUB_OUTPUT

  compositions-test:
    needs: install-crossplane-cli
    runs-on: ubuntu-latest
    if: github.event.pull_request.changed_files > 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find changed composition files
        id: find_compositions
        run: |
          echo "CHANGED_COMPOSITIONS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'control-plane-crossplane/compositions/' | grep -E 'composition|xrd' || true)" >> $GITHUB_ENV
      - name: Run Crossplane unit tests for compositions
        if: env.CHANGED_COMPOSITIONS != ''
        run: |
          for file in $CHANGED_COMPOSITIONS; do
            echo "Testing composition: $file"
            crossplane test $file --sample-composite control-plane-crossplane/compositions/workload-cluster-xrd.yaml || exit 1
          done

  composite-resources-render:
    needs: install-crossplane-cli
    runs-on: ubuntu-latest
    if: github.event.pull_request.changed_files > 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find changed composite resource files
        id: find_composite_resources
        run: |
          echo "CHANGED_COMPOSITES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'control-plane-crossplane/compositions/' | grep -E 'xrd' || true)" >> $GITHUB_ENV
      - name: Render composite resources
        if: env.CHANGED_COMPOSITES != ''
        run: |
          for file in $CHANGED_COMPOSITES; do
            echo "Rendering composite resource: $file"
            crossplane render $file || exit 1
          done

