name: Test Webhook Notification

on:
  repository_dispatch:
    types: [Kustomization/crossplane-composite-resources.flux-system]

jobs:
  test-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Echo notification received
      run: |
        echo "🎉 Webhook notification received!"
        echo "Event type: ${{ github.event.action }}"
        echo "Repository: ${{ github.repository }}"
        echo "Sender: ${{ github.event.sender.login }}"
        
        # Print client payload if available
        if [[ "${{ github.event.client_payload }}" != "" ]]; then
          echo "Client payload:"
          echo '${{ toJson(github.event.client_payload) }}'
        fi
