apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubefed
  namespace: flux-system
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/kubernetes-sigs/kubefed/master/charts
