apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Control-plane cluster - GKE workload cluster resources only
# Platform infrastructure is handled by the main platform kustomization
resources:
  - ../../base/gkecluster-apps-dev